### ISSUE TITLE
PrivateSend - Coin Mixing - Request to Increase Max Denominations

### ISSUE THREAD

**Issue by stephen-cernota** [biblepay/biblepay#10]
It looks like 2000 is set as maximum number of coins you can mix in the Wallet GUI
https://github.com/biblepay/biblepay/blob/fd8db16748a8ae1e38d7bda5692353be00a14918/src/qt/forms/optionsdialog.ui#L266

I found that by adding:
privatesendamount=1550001
to biblepay.conf file, I could reach a max of 999,999 coins to mix
https://github.com/biblepay/biblepay/blob/853affd8c070bfbfd8069abd4e4e8fc83f30afb9/src/init.cpp#L687

It looks like 10 is the highest denomination for mixing though? 
I got a huge amount of addresses with 10.0001 BBP, also 1.00001, 0.100001 and 0.0100001

Given that we are over 100x more coin supply then Dash, 
should we have 100 and 1,000 BBP amounts for mixing available? (maybe even 10,000?)

**Comment by biblepay** [comment]
Thanks, looks like we did this last month!  Thanks for the insight!

Rob

**Comment by sunk818** [comment]
Submitted PR to change default UI values (multiply values by 1k) https://github.com/biblepay/biblepay/pull/43
