### ISSUE TITLE
Add fields for BBP ready to bankroll 

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#100]
I would like to see how much I have BBP ready for bankroll in PoG engine room.
This requires #94 to work first. Otherwise this will be bad for coin age.

**Comment by sunk818** [comment]
What does "ready for bankroll" mean? What's the criteria for being read to bankroll? Is it low coin age? Low coin amount? Or some other criteria?

**Comment by vahtis** [comment]
All the coins without denomination.
Since PODC is removed we do not need to preserve its coins

**Comment by sunk818** [comment]
Ready to bankroll might include tithe change (less than 1.5 BBP) so they can be consolidated during a bankroll. I noticed `exec bankroll` only takes 1 input at a time, so perhaps that needs to be looked at as well.

**Comment by biblepay** [comment]
Both features have been retired.
