### ISSUE TITLE
Create Masternode entry QT client side.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#103]
Since @MIPPL  created the Ubuntu 16 masternode installer script (remote server), it'd be nice to have a client side QT GUI configurator.

It used to be a default feature for DarkCoin. Not sure why they remove it from DASH. It'd make setting up masternodes easier for the uninitiated.

![image](https://user-images.githubusercontent.com/6989799/55126702-0d1b8000-50cb-11e9-9595-5c6532cfec88.png)

**Comment by biblepay** [comment]
Not worth our dev time for the benefit compared to priorities.

You are more than welcome to commit the change.
