### ISSUE TITLE
Change default settings for PoBH mining to off (gen=0)

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#104]
When setting up masternodes on a VPS, having solo mining turned on (gen=1) and minersleep=325 will mean CPU is being used. This will get you kicked off some VPS hosts. Let the people that want to mine, explicitly set it. The current settings is a form of malware that utilizes CPU without permission. This is not that different from how coinhive behaved or any other malware that steals resources without explicit client permission.

**Comment by biblepay** [comment]
I think its more intuitive to automatically mine.

**Comment by sunk818** [comment]
Good luck with that decision. Imagine how every binary will need an explicit exclusion to run on a Windows computer if the binary gets flagged as malware. Talk about adoption drop and making it so easy for grandma.
