### ISSUE TITLE
Taskbar icon improvement

### ISSUE THREAD

**Issue by lunarovic** [biblepay/biblepay#12]
Hello, I think the taskbar icon could use some improvement, because it doesn't look very professional with the square white background, so I made a high quality transparent .ico file for Windows which contains 5 different sizes of the BiblePay logo:
16x16, 24x24, 32x32, 48x48 and 256x256

[taskbar.zip](https://github.com/biblepay/biblepay/files/1667356/taskbar.zip)

So if it fits, maybe it could get added to a future update? :)

Thanks

**Comment by biblepay** [comment]
Thanks, I like the transparency... Checking now!

**Comment by biblepay** [comment]
Alrighty, this required 256x256, 128x128, 64x64, and 32x32, but I was able to shrink the 256's out to the 4 sizes to 4 transparent images, so now we should be good as of the next build.

Thanks for this contribution, we all appreciate it.

Should be in the next build.

**Comment by lunarovic** [comment]
Could you check if this was implemented? Because I still have the taskbar icon with the white background (latest wallet version). Thank you
