### ISSUE TITLE
Update from wallet

### ISSUE THREAD

**Issue by bgalassini** [biblepay/biblepay#15]
Hey, I noticed we're having very frequent wallet updates. That is very cool considering there aren't many projects out there that update their stuff at all. I was wondering if we could make it easier to update the wallet. Siacoin has an update notification built into their desktop wallet that tells you when the wallet is outdated and it provides a link button that immediately downloads the corresponding updated install file. 

Ideally we would have a wallet that has a pop up notification to update and it downloads and updates itself entirely within the wallet, but I don't know how difficult that would be. I'm just starting to learn coding myself and would help if I could. If we could at least get something akin to Siacoin's update mechanism, that would be awesome. Thanks for hearing me out.

**Comment by biblepay** [comment]
Thanks, nice idea.  I have added a notification inside the overview page that shows when we need to update.  Lets talk about auto-update in the future, depending on if we are on stratis or biblepay-qt.
