### ISSUE TITLE
Breakdown of payment from each GSC campaign.

### ISSUE THREAD

**Issue by fogoat** [biblepay/biblepay#16]
I'd like to see a breakdown of the payment per cpk for each daily super block.

If we know the line items that make up the total, it is more clear and easier to troubleshoot if there are any GSC campaign payout issues.

Maybe this exists already?

**Comment by sunk818** [comment]
It seems CameroonONE is based on current status not the specific point in time.

Height 150080 of 34k BBP should show CameroonONE details, but since all my sponsorships are due, this is not being displayed.

```
Height: 150080
Date: 10/8/2019 19:05
Source: Smart-Contract-Payment
Credit: 34 129.46000000 BBP (matures in 97 more blocks)
Transaction ID: 523519680f6efa2b482aadaad54a12e0d0582f6167059912f8383cde3914fa2d
```

```
19:37:52 leaderboard Sunk 150080
19:37:52
{
  "Prominence v1.1": "Details",
  "Block Range": "149670-149875",
  "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 8341395.00": "1.32%",
  "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "Healing": "Diary Entries",
  "Sunk": "prayer",
  "Prominence": "Totals",
  "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 8341395.00, Reward: 4415.160": "1.320%"
}

```
