### ISSUE TITLE
Show exact minimum amounts to reach each level

### ISSUE THREAD

**Issue by capulo** [biblepay/biblepay#19]
could we add some command or extend existing (totalrac) to show exact minimum amounts to reach each level of reward?
for example:
{
  "Command": "totalrac",
  "Total RAC": 109286.66,
  "UTXO Target": 2404306.52,
  "10% Reward Target": 12345.67,
  "20% Reward Target": 23456.78,
...
  "100% Reward Target": 123456.78
}

**Comment by sunk818** [comment]
May I jump in suggest maybe more details about RAC & BOINC related data in general?

Other thoughts are:
1) Total Team RAC
2) Other data points that are involved in estimated daily payout
3) the actuall calculated estimated payout - this would change with each PODC update I assume?

**Comment by 616westwarmoth** [comment]
Total Team RAC would be needed first, and should be added as soon as is feasible. With that data, someone could easily calculate their own potential reward.  However, having the system calculate the other figure (UTXO levels) shouldn't be exceedingly tricky and would help simplify the system for new users.  I would be hesitant to put an estimated payout as new users could misinterpret that and become disgruntled when they get 1% less.

**Comment by sunk818** [comment]
I removed third suggestion about estimated payout. Licht's purepool shows it, but it often doesn't match up exactly so I see your point and extra admin caused by the variance.

**Comment by thesnat21** [comment]
![image](https://user-images.githubusercontent.com/40502058/41810200-0b71d10e-76c0-11e8-9ace-7730df6e9d19.png)

How's this?  Just about ready to submit the pull request.  I want to confirm it's clear enough.

**Comment by thesnat21** [comment]
also added to getboincinfo
![image](https://user-images.githubusercontent.com/40502058/41810308-08f5db62-76c2-11e8-9c64-00c6c3586083.png)

**Comment by thesnat21** [comment]
![image](https://user-images.githubusercontent.com/40502058/41812510-c098db30-76e9-11e8-956a-9075288b41ac.png)

hows this, clear enough?

**Comment by thesnat21** [comment]
![image](https://user-images.githubusercontent.com/40502058/41812522-019e0880-76ea-11e8-8864-3b52c0f05478.png)
How does this look,  make sense?

**Comment by thesnat21** [comment]
@capulo 

I'm not sure why everyone is confused on the chart... :)

if you stake 10% of the reward, you can have a LOT more RAC than if you are staking for 100% the reward.
(ie if you stake 5bbp / rac for min 10%, vs 20bbp/rac for 100%)

I'm trying to work out something that is more clear... i'll post again when i'm ready

**Comment by thesnat21** [comment]
I'm, thinking of a combined function that lets you choose.. removes ambiguity and allows you to "test" values as well

**Comment by capulo** [comment]
or make two functions :)
show bbp leves - which will be calculated based on current rac
show rac leves - which will be calculated based on current staked balance

**Comment by sunk818** [comment]
1) At my current RAC, what is the minimum BBP I need to earn PoDC rewards?
2) At my current RAC, how much BBP would I need for 100% of the reward?

Those are the only two questions I'd want answered.

**Comment by biblepay** [comment]
Great discussion!  Checking...
