### ISSUE TITLE
Create Github Releases for Mandatory Upgrades

### ISSUE THREAD

**Issue by stephen-cernota** [biblepay/biblepay#23]
A requirement to have BiblePay listed on Crypto Bridge Exchange is to use Github's Releases fuctionality

About Releases
https://help.github.com/articles/about-releases/

Creating Releases
https://help.github.com/articles/creating-releases/

**Comment by biblepay** [comment]
Will do - thanks for adding this.

I believe what I will do is set a precedent at releasing MAJOR updates as releases (IE definitely mandatory upgrades, and possibly Mandatory for Sanctuaries also).  

Im going to leave the leisures without Releases for now, as Im erroring on the position that the bots will notify exchanges when we have a MAJOR release.  

IE We will aim to use this tool for signals for Mandatory upgrades, or Sanc upgrades.

**Comment by biblepay** [comment]
OK, our mandatory upgrade is set as a release:
https://github.com/biblepay/biblepay/releases

Let's notify cryptobridge that we are ready to go live!

**Comment by stephen-cernota** [comment]
CryptoBridge has been notified!

**Comment by sunk818** [comment]
Are you going to provide binary downloads as well? Windows, Linux, and Mac for that specific version?  Specific binary releases will also help with regression testing or UI testing where we can compare specific versions.

**Comment by biblepay** [comment]
"Are you going to provide binary downloads as well?"

Yes, uploaded binaries.  Thanks.
