### ISSUE TITLE
Encrypted Wallet begins in unlocked state if using PoDC Unlock

### ISSUE THREAD

**Issue by 616westwarmoth** [biblepay/biblepay#25]
When starting an encrypted wallet (Biblepay Core), if you put in the PoDC Password in the initial pop-up, the wallet actually begins in an unlocked state.  You can lock it immediately and it seems to not affect the PoDC payments (which is the correct behavior) and then also requires the password for normal transactions (which is the correct behavior).

When starting an encrypted wallet, it should always begin in a locked state, even when a PoDC unlock password has been supplied.

**Comment by sunk818** [comment]
In Linux, I use `walletpassphrase` to unlock the wallet. That seems to be the only way for me to heat mine. Is there another command to allow just PoDC updates but keep the wallet locked? 

I feel as long as `utxooverride=-1` is not in biblepay.conf and (and we have Magnitude > 0?), PoDC updates could occur automatically even if we don't unlock the wallet. This way, we can heat mine (PoBH, PoW) just by starting the daemon and not have to unlock the wallet later.

**Comment by biblepay** [comment]
I am unable to reproduce this.  The code looks correct; we don't unlock the wallet after boot using the secure password.

I have an encrypted locked wallet, I boot, I tried both sending from the UI and sending from command line :

Error: Please enter the wallet passphrase with walletpassphrase first. (code -13)

And it still fails;

Please try again.  This might have happened on one of the earliest versions but the logic was improved about 60 days ago...
