### ISSUE TITLE
wallet 1.1.3.6

### ISSUE THREAD

**Issue by bovcan** [biblepay/biblepay#28]
in 1.1.3.6 Recent Transactions are not updated on the main page in the wallet.

**Comment by thesnat21** [comment]
researching.

**Comment by OrbisPictus** [comment]
I havent problem with "not updating". There is just some type of filter and there are visible only "direct" (received or sent) transactions. There are missing tx with PODC payment. It is not that same? Is it possible to bring PODC payout back to title screen?

**Comment by thesnat21** [comment]
I think that's what they meant.   PODC payments are not showing in the "recent transactions" on the main page.

I found the issue, will get a fix for it shortly.

**Comment by thesnat21** [comment]
Ok, found it ... have a solution
Quick question:  Do you want to see PODC updates in the recent as well?

**Comment by OrbisPictus** [comment]
PODC update is not interesting for me... It's enough to have it in tx
detail tab. It would be like a spam :) That's my opinion.
Interesting for me: sent, received, mined, MN reward.

**Comment by thesnat21** [comment]
fair enough.
https://github.com/biblepay/biblepay/pull/29 pull request submitted.

**Comment by bovcan** [comment]
...ok. I found it later in Transaction tab, because at first I was thinking I didnt get podc payment. 
I didn't saw this was removed in "changelog", so I thought it is a bug or smth. It's fine as it is now..

**Comment by thesnat21** [comment]
I would still consider it a bug, items being filtered from the main list, and podc payments missing from "most common"
People are used to seeing PODC payments on the main screen, it iwll be fixed in the next release

**Comment by bovcan** [comment]
good point.

**Comment by biblepay** [comment]
Thanks guys, looking at the solution Snat gave.

**Comment by biblepay** [comment]
Merging, please test this fix in 1.1.4.2.

**Comment by biblepay** [comment]
Looks like it fixed it, great work!
