### ISSUE TITLE
Login Credentials No Longer Working on Pool

### ISSUE THREAD

**Issue by deviedev** [biblepay/biblepay#3]
I have been trying to log into the pool with the same credentials I've used since signing up and am 
 now receiving an error that my username or password is incorrect.

**Comment by gwestwood** [comment]
@deviedev That's not related to this code.  I suggest that you use the contact details listed in this message ( https://bitcointalk.org/index.php?topic=2042657.msg21641204#msg21641204 ) to request assistance and close this issue.

**Comment by biblepay** [comment]
Feel free to send an email to rob@biblepay.org and we will get it resolved!

Thanks!
