### ISSUE TITLE
Proposal amount display in wallet UI

### ISSUE THREAD

**Issue by noxpost** [biblepay/biblepay#31]
Like the other fields which display amounts, the proposal amount should be displayed with the typical spacing every 3 characters. Currently the proposal amount has no spacing at all.

**Comment by biblepay** [comment]
Also, Luke has reported the proposal list gets cut off on monitors of 1024x768.

**Comment by sunk818** [comment]
We need a scroll window?

**Comment by biblepay** [comment]
Yeah, I think there is a way to enable horizontal and vertical scroll bars for the grid parent object, in QT in the form possibly.

**Comment by biblepay** [comment]
I added horizontal and vertical scrollbars to the next upcoming version.  Havent looked at the decimal formatting yet.

**Comment by thesnat21** [comment]
Sorry i started looking at this but the overall layout has some issues.

The inital table is oversized for the form, and doesn't adjust properly to fill.  Let me know when you post the fix,  I would like to do the display more like the recent transactions... I started down this path already but got pulled away by life ;).   i'll be back

**Comment by biblepay** [comment]
Yes, today I also put in the currency format to do the spaces in the amount, let me check it in - I am babysitting right now :)

**Comment by biblepay** [comment]
Now people can see the list on a smaller res monitor and the currency format.
