### ISSUE TITLE
Cannot compile new wallet problem with missing crypto/RandomX/build

### ISSUE THREAD

**Issue by nodecheck** [biblepay/biblepay#33]
New wallet cannot be compiled, following error:

```
../libtool: line 7485: cd: ./crypto/RandomX/build: No such file or directory
libtool:   error: cannot determine absolute directory name of './crypto/RandomX/build'
Makefile:4421: recipe for target 'libbiblepayconsensus.la' failed
make[2]: *** [libbiblepayconsensus.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/git/biblepay/src'
Makefile:11705: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/git/biblepay/src'
Makefile:686: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
build doesn't exist under src/crypto/RandomX/build, seems to be only a buildwin64 directory.

Compiling on Ubuntu 18.04 amd64.

**Comment by biblepay** [comment]
Yes, recently we modified the build instructions to resolve this.
First, please see this wiki page:
https://wiki.biblepay.org/Upgrade_to_RandomX

To address the actual problem, please see this build guide and corresponding change on line 37:
https://github.com/biblepay/biblepay/blob/master/BuildBiblePay.txt

Technically you should only need to execute lines 36-39 then you should be back on track.

Good luck.

**Comment by nodecheck** [comment]
Done that now, got further, but still errors:

```
/usr/bin/ld: cannot find -lrandomx
  CXXLD    biblepayd
collect2: error: ld returned 1 exit status
Makefile:4421: recipe for target 'libbiblepayconsensus.la' failed
make[2]: *** [libbiblepayconsensus.la] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lrandomx
collect2: error: ld returned 1 exit status
Makefile:4527: recipe for target 'biblepayd' failed
make[2]: *** [biblepayd] Error 1
make[2]: Leaving directory '/home/git/biblepay/src'
Makefile:11705: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/git/biblepay/src'
Makefile:686: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by biblepay** [comment]
Hi NC, can you please tell me if it compiled?

Thanks!

**Comment by nodecheck** [comment]
Hi, yes it's working now.  Initially forgot the make, so had a lib linking error, but then realised why.  Issue can be closed now.  All working good.  Updated and syncing chain now.

**Comment by biblepay** [comment]
Thank you, have a great week.
