### ISSUE TITLE
Cannot compile new wallet on raspbian stretch problem with missing chiabls/bls.hpp

### ISSUE THREAD

**Issue by sieb** [biblepay/biblepay#34]
## New wallet cannot be compiled in the last step, following error:

```sh
user@raspberrypi:~/bin/biblepay $ make
Making all in src
make[1]: Entering directory '/home/user/bin/biblepay/src'
make[2]: Entering directory '/home/user/bin/biblepay/src'
make[3]: Entering directory '/home/user/bin/biblepay'
make[3]: Leaving directory '/home/user/bin/biblepay'
  CXX      bls/libbiblepayconsensus_la-bls.lo
In file included from bls/bls.cpp:5:0:
bls/bls.h:14:27: fatal error: chiabls/bls.hpp: File or directory not found
 #include <chiabls/bls.hpp>
                           ^
compilation terminated.
Makefile:10012: recipe for target 'bls/libbiblepayconsensus_la-bls.lo' failed
make[2]: *** [bls/libbiblepayconsensus_la-bls.lo] Error 1
make[2]: Leaving directory '/home/user/bin/biblepay/src'
Makefile:11705: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/bin/biblepay/src'
Makefile:686: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```
### Device specifications

```sh
$ uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

$ gcc -dumpmachine
arm-linux-gnueabihf
```

**Comment by MIPPL** [comment]
This error happens when Chia-BLS library is not successfully compiled in the depends compilation stage. Do you have by chance the output for that step?

**Comment by sieb** [comment]
https://raw.githubusercontent.com/sieb/biblepay-evolution-tester/master/issue%2334.md

**Comment by biblepay** [comment]
Looks like you did compile all the depends libs, I think, including chiabls.

Now just try a compile again, but make sure your machine prefix is referenced in ./configure, like on line 48 here:
https://github.com/biblepay/biblepay/blob/master/BuildBiblePay.txt

Or unless you did get a compile error in depends, please let us know.

**Comment by biblepay** [comment]
Please let us know if it compiled on this machine type.  Technically randomx should work after the randomx height if it did compile.

**Comment by sieb** [comment]
I'm trying again, now on the raspbian "buster", [here](https://github.com/sieb/biblepay-evolution-tester/blob/master/bbp_compiling_raspibian_buster.md) my workflow (incomplete, Berkeley DB compilation) following the [reference](https://github.com/biblepay/biblepay/blob/master/BuildBiblePay.txt) and the [output](https://github.com/sieb/biblepay-evolution-tester/blob/master/bbp_compiling_raspibian_buster_LOG.md) so far. Soon update the evolution.

**Comment by biblepay** [comment]
"libdb_cxx headers missing, BiblePay Core requires this library for wallet functionality"

So I remember seeing this (before using the bitcoin berkeley db repo, that everyone started using for ubuntu - here : sudo add-apt-repository ppa:bitcoin/bitcoin, which probably doesnt work on rasberry pi ) :  please try this part to manually make the berkeleydb first:

sudo apt update
sudo apt install -y git build-essential
wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
tar -xvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix/
mkdir -p build
BDB_PREFIX=$(pwd)/build
../dist/configure --disable-shared --enable-cxx --with-pic --prefix=$BDB_PREFIX
make install
Then:
./autogen.sh
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2" LDFLAGS="-L${BDB_PREFIX}/lib/"

**Comment by biblepay** [comment]
Hi Sieb, I will close for now, please let us know if you get further or if it works now.
