### ISSUE TITLE
28 confirms, but the PODC Payment is in brackets still

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#34]
Is there some UI mismatch here? 

Shows confirmed, but the BBP payment is in brackets still. Should the brackets be gone?

If it is not confirmed yet, should there be a clock on the left column? 

Confused. Hope someone can clarify...

![180811-542pm-capture](https://user-images.githubusercontent.com/6989799/43997374-f9f14c44-9d8d-11e8-871a-7fb08673b71a.JPG)

**Comment by biblepay** [comment]
Coinbase payments require 102 confirms... so it should be gone soon.

**Comment by sunk818** [comment]
Yes, it does go away, but the next daily superblock shows the same. I just thought I report the UI inconsistency. I know its not top of anyone's list, so I understand if it is low low priority.

**Comment by thesnat21** [comment]
I see what you mean.  ill look into it

**Comment by biblepay** [comment]
Reopened.

**Comment by biblepay** [comment]
A PODC payment is a coinbase payment.  So this behavior is correct - coinbases take 102 to confirm.

**Comment by sunk818** [comment]
There should be a clock icon then until 102 confirms are there for that transaction

**Comment by sunk818** [comment]
https://bitcointalk.org/index.php?topic=2388064.msg46304409#msg46304409

> Also, explain that the payment was more than 7 hours ago, but she's still in the Immature status. When will it be on my balance?

![totikk](https://user-images.githubusercontent.com/6989799/46247684-e0103e00-c3c3-11e8-877f-376ed0effad7.JPG)
