### ISSUE TITLE
masternode-install.sh update

### ISSUE THREAD

**Issue by togoshigekata** [biblepay/biblepay#35]
- Disallow Ubuntu 16.04?
https://github.com/biblepay/biblepay/blob/master/contrib/masternode-install.sh#L94
https://forum.biblepay.org/index.php?topic=517.msg8291#msg8291

- Add new wallet link and unzipping
https://github.com/biblepay/biblepay/blob/master/contrib/masternode-install.sh#L177

```
https://biblepay.org/biblepay-lin64.zip
apt install unzip
unzip -o biblepay-lin64.zip
```

- Add optional erasechain?
https://whitewalr.us/2019/biblepay-erasechain-not-reindex.html

**Comment by MIPPL** [comment]
Still supporting Ubuntu 16.04
Classing Linux links supported again
Added -e|--erasechain option to startWallet
