### ISSUE TITLE
Configuration not read biblepay.conf is Mac file format (CR) on Windows QT

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#36]
@thossoma on BiblePay Discord experienced configuration issues on his Windows QT wallet because biblepay.conf was a Macintosh file-format (CR).

https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types

After changing his EOL (end of line) from CR to CRLF, Windows BiblePay QT wallet read his configuration file correctly.

To reproduce:

1. Windows QT BiblePay, Tools, Debug Console, getmininginfo - you should have pool mining, CPID, etc working
2. In Notepad++, save biblepay.conf as Macintosh (CR) via Edit > EOL > Macintosh
3. Quit wallet
4. Start Wallet
5. Tools, Debug Console, getmininginfo - your previous getmininginfo should not match now

![20180814-10](https://user-images.githubusercontent.com/6989799/44132915-6effb68a-a011-11e8-98d3-ea6087139be4.jpg)

![20180814-11](https://user-images.githubusercontent.com/6989799/44132919-745298f0-a011-11e8-8612-d0f892468dfb.jpg)

![20180814-12](https://user-images.githubusercontent.com/6989799/44132920-761d7b32-a011-11e8-8808-df95683357f4.jpg)

**Comment by biblepay** [comment]
People should not be saving a config file in mac format on a windows machine.

If this error can be reproduced on a mac please reopen, but we have mac users now mining thanks to MIPs mac release, so I believe their config is being read.

**Comment by sunk818** [comment]
I dont know where this originates. Let me see if I can test one click miner configuration and see what the hex viewer says

**Comment by nixcamic** [comment]
Can confirm this issue still exists. To clarify, nobody is saving as Mac format on purpose, rather the built in One Click Mining Config is in Mac format on the Windows wallet, so if you start from that Notepad/Notepad++ will automatically insert new newlines in Mac format. The bundled config needs to be fixed.

**Comment by MIPPL** [comment]
I’ll check it.

**Comment by sunk818** [comment]
I tried on 1.4.4.7e and still seems to be an issue. I'm using Windows 10.

https://github.com/biblepay/biblepay-evolution/commit/5f22676f576b98550009a64b756aa658490855b9
