### ISSUE TITLE
Crash after "stop" while mining

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#37]
I had 16 cores mining, sent a stop command and got this:

biblepayd: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.

**Comment by OrbisPictus** [comment]
same here. with "genproclimit": 8.

**Comment by biblepay** [comment]
Btw, does this happen on every stop or just randomly?

**Comment by thesnat21** [comment]
i'd say 90% of the time?

It seems more frequent on higher thread counts.   It almost seems like something clears before the mining threads are interrupted, cannot say for sure.   I tried running in valgrind and it slowed it down too much to be able to reproduce.

**Comment by biblepay** [comment]
Ok, thanks, it almost seems like this started the day I added the 'setpodcunlockpassword' to biblepay-cli.  I seem to recall getting complaints after that when the biblepayd shuts down... maybe.  Not sure yet.

**Comment by sunk818** [comment]
How does one go about troubleshooting this issue? Is valgrind useful?

**Comment by biblepay** [comment]
Yes that would be helpful if someone could help out as we seem to have gotten busy all of a sudden.

Yes, you can run biblepayd in valgrind, and then issue the stop and you should see the assertion in the valgrind output with a line number; please give us the line number and we will find out why it failed.

**Comment by biblepay** [comment]
It would be cool if someone can valgrind the daemon for us (but it must be built from source) and give us the line # of the crash and the module filename.

**Comment by thesnat21** [comment]
Agreed,  but in my previous attempts the client runs so slow in valgrind the issue doesn't occur..

**Comment by biblepay** [comment]
Lets try again someone, to make sure its not a speed issue.  Also please ensure its running from a compiled copy.

**Comment by biblepay** [comment]
Does not happen on Evolution.
