### ISSUE TITLE
Add BTC bech32 support for staking

### ISSUE THREAD

**Issue by jaapgvk** [biblepay/biblepay#38]
I was reading the documentation on the new staking option, and testing some things out.

```
07:39:40
￼
getpin bc1qnx********************************


07:39:40
￼
Address must be 34 characters long.  (code -1)
```

A BTC Bech32 address is in fact 42 characters long. I was wondering if there is a technical reason for not being able to use Bech32 addresses? Or could this address-type also be implemented in staking?

**Comment by biblepay** [comment]
Although Dash (and BiblePay) do not support Segwit internally, we may be able to support segwit staking for BTC.  We recently added BTC multisig address staking.

Could you please paste the full bech32 address so I can test it -- but only if you think you will definitely be interested in using this feature.

**Comment by jaapgvk** [comment]
I see. Thanks for the explanation. I'm definitely interested :)

bc1q-----

**Comment by biblepay** [comment]
Hi Jaap!
So looking at our code, it appears we will be able to do this, I believe.
Could you please upgrade to 1.5.5.3, then try the stake with the bech32 address but add one more parameter to "easystake".


According to the help:￼
[You must specify easystake minimum_bbp_amount foreign_address foreign_amount 0=dry_run/1=real (optional ticker)]

Try this:
easystake min_bbp_amount foreign_address foreign_amount 0 BTC

The param I added was 'BTC' at the end.  I believe that will force it through.

Good luck.

**Comment by jaapgvk** [comment]
Thanks for looking into it Rob!

I have to wait for a few days to be able to test it though, because I just donated all my non-staked BBP a few days ago. So I'll save up 10k BBP, bankroll it, test it, and report back here ;)

**Comment by jaapgvk** [comment]
I tried it, and I'm not getting the '34 characters' error anymore, but it seems the wallet is not getting the foreign UTXO:

```
19:03:24
￼
getpin bc1qnx------


19:03:24
￼
{
  "pin": 65404
}


19:03:51
￼
easystake 10000 bc1qnx------ 0.04--- 0 BTC


19:03:53
￼
{
  "BBP UTXO": "0746a2f6a51f26add6d140d486a730bf3cdb3b9de7ff322b980ababb5a0e3d64-0",
  "BBP Address": "BA8aPfSgLFntcgJKQrXSYnF9rXeS13xZKf",
  "BBP Amount": 10020.58268,
  "Foreign Symbol": "BTC",
  "Foreign Amount": 0,
  "Foreign UTXO": "",
  "Foreign Ordinal": 0,
  "Foreign Value USD": 0,
  "BBP Value USD": 1.974625522228651,
  "DWU": 28.77394848243923,
  "Pin": 65404,
  "pin_valid": false,
  "Error": "The pin is not valid for this receive address.",
  "BBP Signing Error": "The pin is not valid for this receive address."
}
```

**Comment by biblepay** [comment]
I show this address has 0 in it:
http://api.blockcypher.com/v1/btc/main/addrs/bc1qnx5ef7u3pnq8p05d63j7p6wgksxre3ay6kwah3

Please check to see if it is in a block explorer yet and more than 1 deep?

**Comment by jaapgvk** [comment]
Just tried it again, and it seems to be working! 

`
08:32:00
￼
{
  "BBP UTXO": "0746a2f6a51f26add6d140d486a730bf3cdb3b9de7ff322b980ababb5a0e3d64-0",
  "BBP Address": "BA8aPfSgLFntcgJKQrXSYnF9rXeS13xZKf",
  "BBP Amount": 10020.58268,
  "Foreign Symbol": "BTC",
  "Foreign Amount": -----,
  "Foreign UTXO": "001323-------",
  "Foreign Ordinal": 0,
  "Foreign Value USD": -------,
  "BBP Value USD": 2.032993394145984,
  "DWU": 27.21475064178062,
  "Pin": 65404,
  "pin_valid": true,
  "Error": "",
  "Dry Run Mode": true
}
`

(Will update after I stake for real. Have to wait some conformations...)

**Comment by biblepay** [comment]
Praise God!  All Glory to God.

**Comment by jaapgvk** [comment]
Sorry Rob... I can't seem to get it to work. First I thought the wallet didn't let me stake because the UTXO was lager than 10MM BBP (is that a hard limit?), so I cut it up into smaller pieces. But still won't work and I don't know why... There is enough funds in the UTXO I want to use for staking for any fees (and there are also some smaller aged UTXO's in the wallet if needed).

```
`
07:53:30
￼
{
  "BBP UTXO": "ebac80989ce2066ce566a7e29fd04fd54c0086b55145a8ec3bb6c6374b2d6d3a-1",
  "BBP Address": "BPtWKAMxi7jDMJoXj9AF6jhtmWhs3FQyGy",
  "BBP Amount": 9990000,
  "Foreign Symbol": "BTC",
  "Foreign Amount": --------,
  "Foreign UTXO": "00132---------",
  "Foreign Ordinal": 0,
  "Foreign Value USD": --------
  "BBP Value USD": 1981.064492692267,
  "DWU": 400,
  "Pin": 65404,
  "pin_valid": true,
  "Error": "",
  "Dry Run Mode": true
}


07:53:42
￼
easystake 9900000 bc1qn--------- 0.------0 1 BTC


07:53:46
￼
{
  "BBP UTXO": "ebac80989ce2066ce566a7e29fd04fd54c0086b55145a8ec3bb6c6374b2d6d3a-1",
  "BBP Address": "BPtWKAMxi7jDMJoXj9AF6jhtmWhs3FQyGy",
  "BBP Amount": 9990000,
  "Foreign Symbol": "BTC",
  "Foreign Amount": --------,
  "Foreign UTXO": "001323--------",
  "Foreign Ordinal": 0,
  "Foreign Value USD": ---------,
  "BBP Value USD": 1981.064492692267,
  "DWU": 400,
  "Pin": 65404,
  "pin_valid": true,
  "Error": "",
  "Error (Not Sent)": "(Create Transaction) Insufficient funds.Unable to Create UTXO Stake Transaction."
}
`
```

**Comment by biblepay** [comment]
Hi Jaap,

There are a couple rules in this version - first, the actual UTXO chosen must be between 10K & 10MM so yes, that part has to be fulfilled and that part will work for you in your example.
The second rule is there must be at least one coin in your wallet with confirms between 1bbp-100bbp.

To accomplish that just type exec bankroll, with any small amount or value and the wallet will create some change.

Before you do the real easystake again, you can type 'exec getbestutxo 9000000' and it should tell you if it found the coin.  Or do another dry run.

Finally if you enable coin control and take a look at the coins from the GUI you can make sure none are locked that shouldnt be locked...

Good luck.

**Comment by jaapgvk** [comment]
Hi Rob,

Thank you for your patience and your explanation. I wasn't aware that I needed to have a UTXO between 1-100bbp. Is this documented somewhere (I wasn't in the testnet group)? I can imagine others having the same oversight as me. 

All the other conditions were met btw :)

Anyway, I bankrolled it, and it worked this time around!

**Comment by togosh** [comment]
> Thank you for your patience and your explanation. I wasn't aware that I needed to have a UTXO between 1-100bbp. Is this documented somewhere (I wasn't in the testnet group)? I can imagine others having the same oversight as me.

I've updated my guide!
https://wiki.biblepay.org/UTXO_Mining_Setup#Setup

Thank you Rob and Jaap!

**Comment by biblepay** [comment]
Thanks for updating the guide Togo, and, I was also going to say, over the next two days I will look at the code and see about adding a nicer warning message (if they dont have the low utxo), and expanding the acceptable range to include 1-9999 BBP - etc.

And telling the user what command to type if it fails etc.

Thanks!

**Comment by jaapgvk** [comment]
Nice Togo! And thank you very much Rob :) Everything looks alright for me in the leaderboard now.

**Comment by biblepay** [comment]
Hi Jaap,

So I just checked in 1.5.5.4 into prod and I will make a build now.  This gives the user a better response if they do not have a coin to use and tells them what to do next.

Btw, in testnet we also cover the bad response 'invalid pin' when it is not an invalid pin.  If that crops up in prod I will fix that separately (because I think this new message covers that case).

Ill try to make a new one-pager for BBP also that makes this easier for new users as our current infrastructure has changed so much.  The idea is to give them the overview first, then let them drill into better details for each subject.

Have a good one,
Rob

PS Please close if you think this is satisfactory.

**Comment by jaapgvk** [comment]
Awesome Rob! I will test it out when I have some new funds. Also, I think that the one-pager is definitely a good idea. This is such a fast-moving project. I had basically disconnected myself from crypto (and the internet) for a year, and when I came back, there was so much new information scattered all over the place that it was a bit daunting to get back into it.

Thank you!
