### ISSUE TITLE
BBP unit between duffs & mBiblepay show up as ? instead of µ

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#38]
Using 1.1.4.4 on Windows 10 64-bit.

The value between duffs and mBiblepay is showing up as a question mark. Is it supposed to be the micro symbol **µ** (Alt+0181) ?

![fs20180821-22](https://user-images.githubusercontent.com/6989799/44441982-67c48a80-a584-11e8-8429-d0701c286212.jpg)

This seems to be an issue only on Windows? I can't reproduce this on macOS 10.12.6

**Comment by biblepay** [comment]
Fixed in 1.1.5.3.

Thanks.
