### ISSUE TITLE
Add 10% Tithe for Orphans? checkbox does not calculate total required before send

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#39]
In the UI, checking on the 10% tithe for orphans requires 10% more than the amount you are sending.

For example, if you send 1 000 BBP, you need a total of 1 100 BBP before fees to create two separate transactions. If you don't select Inputs, BBP will select for you, but if you select specific inputs, it doesn't warn you that you don't have enough BBP to cover the send transaction and 10% tithe

![fs20180904-28](https://user-images.githubusercontent.com/6989799/45070488-57cda000-b086-11e8-9a29-62154f08c4ac.jpg)

**Comment by thesnat21** [comment]
Good catch, will try to look at this in a bit

**Comment by biblepay** [comment]
Ok good, will wait for TheSnats pull.

**Comment by biblepay** [comment]
Snat, I'm going to look at this OK?

**Comment by biblepay** [comment]
OK, yes I had to put in a question for the IPFS fee in the same place anyway.

OK, this is fixed - will be in the next version.

**Comment by thesnat21** [comment]
Thanks  Rob
