### ISSUE TITLE
Proposal Add requires unlocked wallet

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#40]
I tried to submit a proposal, but after I filled out all the forms, I was noticed that I needed to unlock my wallet. Then all the form information disappeared and I had to type it in again. 

It'd be nice:

- to know you need to unlock the wallet to add a proposal
- or give a way for you to unlock the wallet temporarily
- do not clear the form data if proposal is not created successfully

I'm thinking giving a message box saying you need to unlock the wallet beforehand is easiest to do?

**Comment by biblepay** [comment]
Great, I made it only clear the screen if it is a successful submit, and I added an explanation to the bottom of the screen to ensure the wallet is unlocked before clicking submit.

1.1.5.3.
