### ISSUE TITLE
Proposal Submitted Successfully stretches window size of QT wallet

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#41]
The QT wallet will not let me shorten the width now that the proposal was successfully submitted. 

Even if I go to another tab, I can't resize the width to make it shorter.

I have to restart the QT wallet for the message to not appear which allows me to resize the QT wallet like before.

![fs20180904-30](https://user-images.githubusercontent.com/6989799/45076287-9f602600-b09e-11e8-9c3f-9dce11cf0d2a.jpg)

**Comment by biblepay** [comment]
Thanks, added breaks to the message, so now it should not widen the screen.

This will be in 1.1.5.3.
