### ISSUE TITLE
Proposal Add did not go through the first time, second time successful

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#42]
First proposal I sent for 2 500 BBP was processed, but never appeared in QT wallet under Proposals

http://explorer.biblepay.org/api/getrawtransaction?txid=073fa80dd665621656b1f178af09a19d7f2b200e24e40811e0df335e833d402c&decrypt=1

I waited 5 days and submitted the same proposal again.

This time, it appeared in the Proposals list. Not sure why this happened, but I thought I let you know:

http://explorer.biblepay.org/api/getrawtransaction?txid=09228b6bdfdc6cf64cb140fc408d1d51401bc2881ff54e5284c3ad994cbb83c2&decrypt=1

**Comment by biblepay** [comment]
If you close the wallet before the collateral is 6 blocks deep, the request is lost.

Please if you can reproduce in an exact manner with full instructions, please re-open.
