### ISSUE TITLE
1.1.5.4: InstantSend error: InstantSend doesn't support sending values that high yet.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#44]
First box: `InstantSend doesn't support sending values that high yet. Transactions are currently limited to 500000 biblepay.`

Second box: `Transaction creation failed.`

I get this error even though the amount I send is less than 500k. 

I tried paying transaction fees from normal to fast... but nothing worked.

![fs20180924-43](https://user-images.githubusercontent.com/6989799/45992407-7fd57100-c03e-11e8-9755-48b09266fb56.jpg)

**Comment by biblepay** [comment]
To fix this, just click on Coin Control and select some source coins worth less than 500,000 bbp.

**Comment by biblepay** [comment]
Thanks, you make a great point.  I think we need to increase the IX limit :).

Alright lets take a look at that next.

**Comment by biblepay** [comment]
Ok, the instantsend value has been increased to 5,000,000.  Please try in prod.

(It was a dynamic spork setting so it's live).
