### ISSUE TITLE
Error on issuing 'stop' command

### ISSUE THREAD

**Issue by gwestwood** [biblepay/biblepay#5]
I'm getting an error whenever I issue a stop command under Linux.  It has been present at least since 1.0.3.1, but possibly earlier:

user@server$ ./biblepay/bin/biblepay-cli stop
Biblepay Core server stopping
user@server$ terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called recursively

**Comment by gwestwood** [comment]
I thought that this had stopped happening, but it still occurs occasionally.  Built on Debian Wheezy (old), I will test on the current stable version and possibly on Ubuntu.

**Comment by biblepay** [comment]
Thanks, is it still happening guys?

**Comment by gwestwood** [comment]
I've not been running Linux daemons/test MNs for a while now, so can't confirm either way unfortunately.

**Comment by sunk818** [comment]
It happened for me running the Linux package binary (by Licht) on a ARMv7 bare metal servers. So, compiling from source seems to remedy that error for me. 

@gwestwood what's your particular setup and can you explain whether you installed the package binary and was the server you installed based on Intel x86 or ARM processor?

**Comment by gwestwood** [comment]
I compiled (from the github code) and optimised it for the Sandy Bridge x86_64 CPU architecture.  I was running it on an up-to-date Debian Jessie Linux install, so was unable to use the pre-compiled version due to library dependencies.

**Comment by biblepay** [comment]
Thanks, I strongly believe I caused the stop issue when I was working on the podc unlock feature.  It had something to do with asking the headless user for the password on-demand.  I remember I moved that feature over to the the biblepay-cli tool (so it would be on demand not modal).

I believe this is now fixed.
