### ISSUE TITLE
unbanked payments missed

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#51]
opening issue for this,  sunk818 and I missed ours again last night.

It had been going well the last week or so.

**Comment by sunk818** [comment]
Here is a comparison of payment from Oct 26 vs Oct 27:
[oct26-vs-oct27.txt](https://github.com/biblepay/biblepay/files/2522465/oct26-vs-oct27.txt)

I found 22 BBP addresses that are missing from Oct 27 payment.

[oct26bbp.txt](https://github.com/biblepay/biblepay/files/2522463/oct26bbp.txt)
[oct27bbp.txt](https://github.com/biblepay/biblepay/files/2522464/oct27bbp.txt)

**Comment by thesnat21** [comment]
this should be fixed with the new unbanked process
