### ISSUE TITLE
Proposal list in GUI data filtering issue

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#56]
The proposal list should filter old/past proposals.

Adding sorting options would be nice as well. (ex: by date created, # votes etc)

**Comment by biblepay** [comment]
Ill take care of the filtering out of past proposals next.

Ill probably leave the sort by for someone else to do.

**Comment by biblepay** [comment]
OK, I did modify the next version to filter down to Active proposals - these are proposals that are applicable to be paid in a future superblock.

I also made it sort by Added date ascending.

If anyone wants to modify the grid to be clickable to sort by any column, feel free.

**Comment by biblepay** [comment]
I suppose we tackled this one for now, please add a new issue when we want to do the cadillac enhancement.
