### ISSUE TITLE
Enhance: Put Proposal Add within Proposal

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#57]
This is an enhancement request for the Proposals Add button. I think Proposals Add does not need its own left column button in the GUI wallet. Add as a top button with Proposals list. When someone clicks on Proposals Add, the form field to enter in the specifics appear.

**Comment by biblepay** [comment]
Sounds like a good idea.  We put the Add on the menu because we were lazy at the time.

**Comment by biblepay** [comment]
OK Proposal add is moved to the top menu.

Will be in the next release.
