### ISSUE TITLE
Enhance: Make Proposal list build data only from blockchain not third-party nor proxies

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#59]
I want to see Proposals (duplicates and all) build a list of proposals for pending (e.g. current) monthly superblock. I'd also like to see past proposals built off the blockchain only. No business logic to hide duplicate proposal names retrieved from a third party like pool.biblepay.org . Proposal list should accurately reflect all proposals added to the blockchain (mistakes and all).

**Comment by biblepay** [comment]
The proposal list does show duplicates if we have duplicates.

The proposal list does not rely on outside sites (pool.biblepay.org relies on biblepay-core).  Btw, "pool.biblepay.org" is not a 3rd party site - its our official pool.
