### ISSUE TITLE
Restrict wallet "upgrade" notification to production only releases.

### ISSUE THREAD

**Issue by thesnat21** [biblepay/biblepay#60]
Someone commented on this,  I think it's a good idea :)

**Comment by vahtis** [comment]
If we have separate download page for testnet I think this is not needed.

**Comment by thesnat21** [comment]
Was thinking that after I put this up...  Either method works, but if testnet vers are having issues better not to have it floating around production just in case.

**Comment by sunk818** [comment]
I think having binaries for windows is nice for ease of testing. If the testnet has different url to download then only those that seek it out are downloading it. No adverse affect running latest version in production but I suppose it's like Russian roulette :)

**Comment by MIPPL** [comment]
We are already working on it to separate master/develop branches for prod/testnet respectively.

**Comment by sunk818** [comment]
I'm having issues with StakeBalance showing up as 0 when I run `exec totalrac` on 1172b in Prod. I'm not accusing nor know enough about the code to know, but just pointing out odd behavior since I upgraded from 1166. I have over 2M BBP, but none of it is recognized for PoDC reward:

https://forum.biblepay.org/tools/podcstatus.php?cpid=c3939b61e69c6bde1eddb06708e0f96e

**Comment by biblepay** [comment]
So MIP and I spoke at great length about this and decided it is a good idea to do this in two phases.  Phase 1 :  Rob has deployed a fix where the core client will now locate the last mandatory in Prod, and only notify the user if the client is outdated as compared to the last mandatory.

Over the next 6 months, MIP is going to look into our build scripts to locate a compiler tag that designates which branch built the core client.  This way the core can also ignore the github version if the branch is not "main".

MIP feel free to re-open after the dash rebase is finished to finish phase 2.

**Comment by biblepay** [comment]
EDIT:  In the next version, we have the ability to detect if the core version was built on a dev branch.  Starting in 1197, the GetGithubVersion will also respect this flag and not show the false upgrade notification.
