### ISSUE TITLE
Sun missed 4 unbanked podc payments

### ISSUE THREAD

**Issue by biblepay** [biblepay/biblepay#64]
Missed unbanked PoDC payments for 1/4, 1/2, 12/27, and 12/25. 
[/quote]

I show more than 10 unbanked cpids were voted in on the blocks above, except I dont see a PODC superblock that fell on 12-25 (we had one on 12/24 and then 12/26)

CPID?[/quote]

https://forum.biblepay.org/tools/podcstatus.php?cpid=12adc617474710035a0be614454e7251
[/quote]

Your cpid was in my sanc1's contract on all 3 of the blocks, therefore the unbanked code is working correctly.

My theory is the sanc that solved these 4 blocks is behind a VPN (or has HTTP blocked), and is therefore not downloading the unbanked report.

The only way we can tell for sure is if we add a couple hours of code into the sanc contract (and a mandatory sanc upgrade), this would populate the governance object with additional details (as to what unbanked info was pulled).

Info:  Superblocks where height in ('93490',92875,91645) and unbanked=1

**Comment by thesnat21** [comment]
Would it help to put the HTTP report on a different port?
Obviously we can't use 40000... I wonder if there is another we could try.

**Comment by biblepay** [comment]
No, on the port #, because that doesn't necessarily address the problem.

On chain message, anything is possible given enough time and resources.

I think the best baby step is to continue to add the debug info to the gov object to give us some kind of idea what is going on when someone solves the block without unbanked info, then we can make a next decision.

**Comment by biblepay** [comment]
Waiting for the outcome of the to retire / not to retire PODC decision on this.  If we dont retire, we could probably add the contents of the unbanked query into the gobject field as the first baby step, then when someone misses one we can at least see if that sanc honored the list or not.

**Comment by sunk818** [comment]
I have many Android phones, but with so few users on "unbanked" system it is not really worth the effort to maintain IMO. If on the rare chance PoDC stays on, I don't see the point in keeping "unbanked" around. Even though I would be negatively affected, I can see other things taking higher priority in BiblePay.

**Comment by biblepay** [comment]
PODC has been retired.
