### ISSUE TITLE
PODC has wrong amount

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#65]
PODC update seems to be sending wrong utxo weight amount. 
 I have 48k bbp in wallet and updates have been around 31-33K

https://www.biblepay-central.org/en/podc/user/1991402/

**Comment by thesnat21** [comment]
Based on this review, you are fine.
https://forum.biblepay.org/tools/podcstatus.php?cpid=252455be172ea3aa289d1237fce91818

I will let Rob comment if he wishes, but I believe there is a cap at 124/125% PODC stake.  No need to send more than that

**Comment by vahtis** [comment]
Need to find out why my RAC is decreasing

**Comment by vahtis** [comment]
Have a look now. 
https://forum.biblepay.org/tools/podcstatus.php?cpid=252455be172ea3aa289d1237fce91818

```
> Min Required Stake:1,103
> Min Stake last 24hr:5,402
> Most Recent Stake:31,769
> Estimated PODC Reward:20%
> Actual Stake:20% 
```

**Comment by thesnat21** [comment]
Interesting,  what is your config setup as, and which version are you running?

**Comment by vahtis** [comment]
Date does not match. Problem was 9th.
I have multiple wrong updates too. You can see from my PODC payment history that I now and then get lower payments than usually.

Wednesday 09. January 2019
--
94417 | 23:23:21 | 31,967 | 5efa32c64dfdd21e0b05848945b15f9f403360b6c102b1677020c86e9d429966
94378 | 18:41:37 | 32,626 | 9f5aee364ddb718beb05a2a76ba055ccfba1f369d1d2081e3a6ebf484e468eef
94342 | 14:24:27 | 5,411 | 6ede656ba217ba3b116c05ee0a641dd240aaff4a8c90caa327d8f6d1e780b974
94311 | 10:12:28 | 32,627 | 1db7f4e8db836e8cf4fd6a96149efeafc97b6baa6c933cf23fffc0e82c849a16
94273 | 05:54:33 | 32,729 | f3faa455ae909da27b0863248558d7732dd6f1f097337430465107054b7537e5

**Comment by thesnat21** [comment]
unfortunately this is something we need Rob to look into..

**Comment by sunk818** [comment]
@vahtis PoDC updates can have a lag of 24-48 hours, so WCG maintenance on 8th and your issue on 9th is correct. It didn't impact what you got paid in BBP, it was a glitch that I can directly attribute to WCG maintenance.

Your second comment about BBP being lower than "usual" has nothing to do with what you reported. Lower than "usual" is normal. When more RAC joins the team, you will receive less BBP because your percentage (RAC / team RAC) is lower.

**Comment by biblepay** [comment]
Vahtis for now please enter 'utxooverride=nnnnn' so you dont get shortchanged.

**Comment by vahtis** [comment]
I added utxooverride now.
