### ISSUE TITLE
PoG Leadboard does show up in production

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#67]
We have reached block 100k. QT Wallet was restarted. Running 1185b. PoG Leaderboard should appear as GUI item, but is not appearing. `pogpool` command in debug console works. Currently shows 21 participants (donations from last 205 blocks seem to be recognized)

**TESTNET:**

![image](https://user-images.githubusercontent.com/6989799/52384520-b1ba0380-2a32-11e9-962e-6d74f2a48d98.png)

**PRODUCTION:**

![image](https://user-images.githubusercontent.com/6989799/52384591-00679d80-2a33-11e9-8eec-df2dc1b4271a.png)

![image](https://user-images.githubusercontent.com/6989799/52384614-1a08e500-2a33-11e9-9949-db69bfa6af2e.png)

**Comment by biblepay** [comment]
Thanks a lot, fixed.

**Comment by sunk818** [comment]
Fixed in 1.1.8.6: https://github.com/biblepay/biblepay/commit/e3c8d2f17ac772fa5a1d5e576726c247532b00f3
