### ISSUE TITLE
enhancement: pogpool and GUI leaderboard sort by block height

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#69]
Hi, would it be possible to see `pogpool` sorted by blockheight (greatest blockheight at top)? For the PoG Pool GUI, same would be good. The reason is that you can analyze better when the block height is sorted. We can see when a contribution, especially 10k tithing, will drop off.

I also think payment tier column is unnecessary at this point.

**Comment by canopussy** [comment]
good point +1

**Comment by OrbisPictus** [comment]
If I understand it correctly, the "height" is sowers "oldest" tithe in pool. And it may not be the "highest". But yes, as good drop off watch point it is good. It would be awesome to have possibility to sort POG leaderboard in GUI, but best would be to choose sort option by your choice (any column).

**Comment by biblepay** [comment]
I removed that payment_tier last night, and made the GUI version sort by Highest Tithe descending (since its a leaderboard).

Let me see if I can sort the RPC version by amount descending now...

**Comment by biblepay** [comment]
Your 100249 tithe will probably show up in 4+ blocks.  Its always 4 behind.

**Comment by capulo** [comment]
pool is already sortable by any column, but there is some refresh every few seconds and after refresh it is back on default sorting - e.g. selected sorting is not remembered
second problem is that not only user row are sorted, but also summary and white lines
third thing, it could be useful to have some checkbox for removing data from previous block - these data are useles for current block and i'm only interested in current block and not messed up data with previous block

**Comment by MIPPL** [comment]
I'll take a look at this one, thanks for the feedback

**Comment by OrbisPictus** [comment]
And when you sort by amount, the output is bad. My output is here: https://prnt.sc/mmsix5

**Comment by MIPPL** [comment]
Fixes: 
- sort by amount
- remember order column after refresh

Not fixed:
- can't ignore blank and summary lines from ordering. Perhaps we can remove those lines from leaderboard and let user check it at new PoG Engine Room screen.
- data is refreshed completely when the refresh interval is reached (120 seconds), so there should be no information from previous blocks, or I don't understand under which conditions info from previous blocks can be shown. A sample screenshot would be appreciated.

**Comment by capulo** [comment]
sorry, by previous block i meant previous payout blocks. so something what shows only data after payout block e.g only data relevant to next payout. if payout was on block 96200 then it will shows only data for 96201+

**Comment by sunk818** [comment]
@MIPPL the PoG GUI leaderboard will not scale well as participants grow. Is it wise to set a limit on top participants? Maybe show full list for cli pogpool?

**Comment by MIPPL** [comment]
@capulo what you ask might depend on some network propagation time factor, so what happens if we have a PoG reward block and after some minutes it's rejected because there is another block accepted with more work or consensus... At this moment I would just rely on the contents of the PoG pool to create the list, and let the network decide when the new pool must be constructed (and as soon as it is available, the PoG leaderboard will be refreshed accordingly).

@sunk818 it should scale well up to 2000-3000 users. We can see it develop and address it if we find bottlenecks.
