### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by svirusxxx** [biblepay/biblepay#7]
with 1.0.3.9b I don't have any problem with compiling
but latest 1.0.4.0b show me this error:
``
  CXXLD    biblepayd
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../lib64/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
``

Os Gentoo , gcc 5.4.0

**Comment by svirusxxx** [comment]
on gcc 6.3.0 I don't see this problem

**Comment by biblepay** [comment]
Got it, fixed.  Thank you for the contribution!
