### ISSUE TITLE
PODCUpdate: Unable to locate coins not marked as POG bankroll denominations.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#70]
Using 1185. I am unable to perform an `exec podcupdate`. 

`18:40:06 exec podcupdate
18:40:21
{
  "Command": "podcupdate",
  "PODCUpdate": "Unable to locate coins not marked as POG bankroll denominations."
}`

I have enough non-tithe BBP to do an `exec podcupdate`

![image](https://user-images.githubusercontent.com/6989799/52456551-201dc500-2b0a-11e9-9029-9d8bf7a62081.png)

I also tried the following, but results did not change:

1) unlock wallet completely
2) put `utxoamount=1400000` and restart BiblePay QT wallet

**Comment by biblepay** [comment]
Could we try to rule out two things first.

1) How old is that 1,451,230 coin?  It needs to be over 6 confirms for it to be searched.
2) Could we have you send yourself that 1,451,230 coin back to you in a couple of transactions so you have 1 mil + 450,000 in there, then try again?    This might rule out the ending suffix amount.

**Comment by sunk818** [comment]
Coin had more than 6 confirmation (fully confirmed).

I tried sending myself various amounts in the past without any differing results.

I ended up making a virgin wallet, and perform exec associate after I sent BBP to the new wallet.

`exec podcupdate` ran perfectly.

I'm beginning to think there's some conflict with PoG.

**Comment by sunk818** [comment]
If I have any balance in a PoDC address, `exec bankroll` was failing for me. This will eventually go away if PoDC is retired, but it does complicate things for people that choose to use one wallet for PoDC and PoG. If the issue is too complicated or resolve itself, I can tell people to use separate wallets.

**Comment by biblepay** [comment]
So why are we talking about exec bankroll, if this ticket is for the inability to send a podc update?
Please enter a separate ticket for exec bankroll.

Should we close this, please confirm there are no problems with podc updates?

**Comment by sunk818** [comment]
`exec podcupdate` will fail if I have any balance in TITHES address. The easiest way to create balances in TITHES address is by using `exec bankroll`. Since you closed this issue, I will take that to mean you are not interested in further details surrounding `exec podcupdate` nor `exec bankroll`.

**Comment by sunk818** [comment]
I believe tithes created using `exec bankroll` is conflicting with PoDC updates. Its just a theory at this point. If I'm motivated, I will document the steps to make this reproducible.

**Comment by OrbisPictus** [comment]
I have same problem. 
`Command": "podcupdate", "PODCUpdate": "Unable to locate coins not marked as POG bankroll denominations.` 
Coins are old enough, I've tried to send it to myself in more than one tx, but it didn't helped.
Only one thing that helped me was `utxooverride=xxx` setting in config, but I don't like it, because utxo can vary and I don't want to have fixed value there.
Till few days ago it was all working without problem (I have PoDC and POG on same wallet), but after my CPID expiration problem, PODC update stops working.

**Comment by sunk818** [comment]
Unable to perform exec podcupdate . There's an error that says:

PODCUpdate : Unable to location coins not marked as POG bankroll denominations.

![image](https://user-images.githubusercontent.com/6989799/53822373-73760e00-3f24-11e9-82c6-5e2f968b69da.png)

Only balance outside of Rosetta address is shown here.

0.37 BBP is outside of Rosetta address if you look at Coin Inputs using Tree mode.

![image](https://user-images.githubusercontent.com/6989799/53822382-783ac200-3f24-11e9-9c5e-7078ac53100b.png)

Moved non-Rosetta balance to Rosetta address
![image](https://user-images.githubusercontent.com/6989799/53822391-7cff7600-3f24-11e9-8a17-8db6b9b388b3.png)

Perform exec podcupdate again or wait for BiblePay wallet to do it automatically.

Now exec podcupdate works. 

You see all balances are combined and the denomination < 1 is change.

![image](https://user-images.githubusercontent.com/6989799/53822404-82f55700-3f24-11e9-915a-fe3e2c79730c.png)

**Comment by sunk818** [comment]
dave_bbpdave_bbp suggested the following:

> I had this problem too. I fixed it by creating a "receiving address" named PODC (or something similar) and sending the amount of coins I wanted to use for PODC updates to this address (I chose mostly small inputs in coin control for that, but it doesn't really matter). Then add the following line to your config:
> utxooverride=XXXXXXXXXX
> 
> 
> with XXXXXXXXX being the amount of BBP you want to stake for PODC. In your case 400000 should be enough.
> 
> After restarting it sent PODCupdates again and it does so until now (wallet 1198).
 
Source: https://bitcointalk.org/index.php?topic=2388064.msg50035622#msg50035622
