### ISSUE TITLE
Clear on network clears only screen not the values

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#72]
If i press clear on windows wallet it only clears network traffic 
![image](https://user-images.githubusercontent.com/10445226/52517342-d84e8900-2c42-11e9-9f2c-de19c569c724.png)

**Comment by sunk818** [comment]
This is an upstream issue. Even on latest DASH 0.13.1, the behavior is the same. Clear clears the bar chart lines and resets the y-axis. Clear does not remove the totals. To that, you have to restart the wallet.

![image](https://user-images.githubusercontent.com/6989799/53221257-7700bf80-361d-11e9-8c07-ce26f25afef9.png)

**Comment by biblepay** [comment]
Will someone please tell us if this is fixed in Dash Evolution (IE the new release they are testing in testnet)?

**Comment by biblepay** [comment]
Please reopen in the Evo thread if this is still an issue.
