### ISSUE TITLE
PoG Leaderboard - right click View makes QT wallet gets stuck

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#73]
The GUI for PoG leaderboard seems to share the Business Objects logic in some places. If you right click on PoG leader board line item and select View, the QT wallet gets stuck. It eventually times out says something about Business Object not found.

<img src=https://user-images.githubusercontent.com/6989799/52734550-60ea6380-2f7a-11e9-9816-f216bae87616.png width=200>

Right click, Navigate and Right click, List don't seem to do anything.

**Comment by MIPPL** [comment]
Contextual menu removed in pog leaderboard mode.
