### ISSUE TITLE
1.1.8.8 viewing PoG leaderboard causes crash if syncing blockchain <100k (pre-PoG)

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#74]
cuarc001 on BTC talk said:

> Windows 10 Pro x64 with latest updates.
>
> tonight I restarted my VM with my wallet running 1.1.8.8. After doing so, it said out of sync and said it was over a year out of sync. Odd but ok. However, the "bug" I'm finding is if I click the link for the POG leaderboards before it is done syncing, it will crashed the wallet. I'm assuming it is because we didn't have PoG back then. I also notice that my "tithes" awards aren't currently showing up as tithes in the list yet. I will report back after it finishes syncing.
> 
> Edit: I can also reproduce this on a different system I have as well if I'm resyncing from the beginning.  

Source: [https://bitcointalk.org/index.php?topic=2388064.msg49779119#msg49779119](https://bitcointalk.org/index.php?topic=2388064.msg49779119#msg49779119)

**Comment by MIPPL** [comment]
I reproduced the crash also on MacOS debugger so I'll address it

**Comment by MIPPL** [comment]
fix commited to develop branch (3bde040878f3c2febf675c0e075a7616e70be392)
