### ISSUE TITLE
Update help command in debug Console

### ISSUE THREAD

**Issue by nsummy** [biblepay/biblepay#75]
If you open the debug console and type help, it excludes many helpful commands that are needed with dealing with POG. PODC, etc.  It would be nice for the list to include every single recognized command

**Comment by sunk818** [comment]
Do have a list of commands that you are not seeing? They are interspersed. And they might be incomplete.

**Comment by nsummy** [comment]
There are so many that are missing the question is more like, which ones are you seeing?  

for starters: 

tithe tithe_amount min_coin_age min_coin_amount  - Tithe is there, but fails to specify required variables
exec getdimensionalbalance min_coin_age min_coin_amount
exec bankroll quantity denomination


Beyond that it would take me a lot of scouring and I don't know whats missing if I've never see the full list.  I do know that whenever there are wallet problems I always see solutions in bitcointalk that involve running commands that are not documented in the help command.  Furthermore how long has podc been around and those commands still aren't in there?!

**Comment by sunk818** [comment]
@nsummy thanks for the specifics. Let me study what @thesnat21 did and make a pull request.

PoDC commands are available if you type `help exec`.

**Comment by sunk818** [comment]
[Rob said](https://bitcointalk.org/index.php?topic=2388064.msg49858516#msg49858516:)

> Also, please run the `exec pogdifficultysimulation` in the next version.  It will show a simulation per difficulty level with each of the tithe difficulty parameters per range.

**Comment by biblepay** [comment]
@nsummy If you are a programmer this is the kind of thing you can do for us.

**Comment by biblepay** [comment]
The majority of these RPC commands have been removed in Evo.
