### ISSUE TITLE
The auto-tithe feature was only tithing 90%.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#78]
@capulo said:

Manual PoG Tithe allows 9, but auto tithe only donates 8.1

![image](https://user-images.githubusercontent.com/6989799/53204087-a395e680-35df-11e9-9f94-9ee832c1c8e0.png)

Rob answered:

> Your correct, auto-tithe was only tithing 90%.  Fixed in this next leisure.

Source 1: https://bitcointalk.org/index.php?topic=2388064.msg49857551#msg49857551
Source 2: https://github.com/biblepay/biblepay/issues/77#issuecomment-466172460

**Comment by biblepay** [comment]
This should be fixed in 1192; compiling...

**Comment by sunk818** [comment]
Thanks. https://github.com/biblepay/biblepay/commit/6f79cdfea2871865a14df42babe45d0096307041
