### ISSUE TITLE
Enhance: tithe output have one .001 output and the other output < 1 bbp

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#79]
vahtis said:

> This is the thing I asked as new feature too. 
> When tithing 8 bbp from lets say 
> 2000.001 BBP coin  it would be very nice to have 1992.001 BBP coin left
> 
> This would work only for integer tithes.

capulo said:

> yes, something like vahtis  wrote
> 
> this is my case . 
> i had 500k, i did bankroll 100 5000. i already send one tithe from every pile (manualy or autotithe) and this is my actual state:
> 
> ![image](https://user-images.githubusercontent.com/6989799/53272591-942da080-36a6-11e9-8a05-72190aa3576e.png)
> 
> as you can see, there is no .001 suffix. so now i'm affraid if i use bankroll again, it will take these piles as they dont have .001 suffix

Rob answered:

> when we create the Tithe transaction, instead of sending back the regular change, we do it like this:
> 
> User has 1000.001 bbp in the wallet
> User wants to tithe 3.05 bbp
> 
> Right now we send 3.05 bbp to Foundation and receive back change of 996.951
>
> instead, we should:
> 
> A->To Foundation->3.05
> B->To My "TITHE" address->996.0010
> C->To ChangeAddress->.95
> 
> It should work like this for all tithes.

[https://bitcointalk.org/index.php?topic=2388064.msg49872226#msg49872226](https://bitcointalk.org/index.php?topic=2388064.msg49872226#msg49872226)

**Comment by biblepay** [comment]
Please test to ensure 1.1.9.3 completes this; in my testing it was successful.

**Comment by sunk818** [comment]
@biblepay I can't test because I don't any have any eligible coins in production. And can't find peers on testnet. I assume it is working. I will re-open if coin outputs are not as described.
