### ISSUE TITLE
exec bankroll: Signing transaction failed on locked wallet

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#83]
The error message is not clear. I had to unlock my wallet to perform the `exec bankroll` denominations correctly. Perhaps more wording to suggest unlocking the wallet?

```
22:03:48 exec bankroll 40 5000
22:03:50
{
  "Command": "bankroll",
  "Error": "Signing transaction failed"
}
```
![h190224-04](https://user-images.githubusercontent.com/6989799/53317425-6308c800-3880-11e9-92d1-a750b48d212f.jpg)

**Comment by biblepay** [comment]
Ok, I added an extra verbose message for this case in 1195.
