### ISSUE TITLE
report, total incoming & outgoing per day with daily CMC closing value.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#85]
For tax purposes, it'd be nice for BBP to show total outgoing (e.g. auto tithe) that left your wallet and total incoming (e.g. PoG reward) by day. With this, we could use use [CMC Historical Data ](https://coinmarketcap.com/currencies/biblepay/historical-data/) daily close value and figure what our "income" and "expense" were for tax purposes.

I realize crypto taxes a little more complicated since you make assumptions about what you sold (FIFO, LIFO, and cherry pick line items), but it'd be a start to know BBP holdings and total inflow & outflow per day.

I see that CMC does have an API but basic users do not get historical data, so I think having a guide showing how to merge BBP data with CMC historical data on a spreadsheet will have to do.

**Comment by biblepay** [comment]
This is not something I'm interested in adding to biblepay this year.
Please re-enter after we fulfill the current roadmap.

In the mean time you can help by finding us a debit card provider if you need something to work on.
