### ISSUE TITLE
mypogaudit - shorten characters per line

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#86]
Thanks for `exec mypogaudit` - its a very helpful tool.

I'm wondering if you can provide a legend at the top?

So **Legal** 1 or -4 just needs the value if the legend is printed beforehand.

I think other codes like **min coin value** could -> **mcv**, **min coin age** -> ### mca and put those codes as legends above the data.

![h190227-10](https://user-images.githubusercontent.com/6989799/53540313-e406d000-3ac9-11e9-876a-53e4304a77f6.jpg)

**Comment by biblepay** [comment]
This is not worth any of the devs time.
