### ISSUE TITLE
Outdated masternode_conf.md

### ISSUE THREAD

**Issue by stephen-cernota** [biblepay/biblepay#9]
biblepay/doc/masternode_conf.md

collateral should be changed from 1000 to 1550001

Maybe reference these 2 guides?
http://wiki.biblepay.org/Create_Sanctuary
http://wiki.biblepay.org/Create_Sanctuary_2

**Comment by biblepay** [comment]
Checking....

**Comment by biblepay** [comment]
Fixed!

Thanks!
