### ISSUE TITLE
PoG tithe? GUI values do not reflect pogbuffer multiplier

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#91]
I hope I am explaining correctly. Even though I am not showing `titheinfo` or `exec getdimensionalbalance 0 0` output, I hope you can reproduce the same situation. So, my tithable min coin age or min coin amount is very close the minimums stated. I believe with the pogbuffer value (I have mine set to 10%), the manual tithe through the GUI fails. So, this is working as intended.

The GUI values (the red text). Do you think this value should reflect the values *after* pogbuffer multiplier is performed? I'm also think there is impact to PoG engine room display values? @MIPPL 

If you need more data, please let me know. It may take several days though for me to encounter this specific situation again. In other words, please do not close issue if you think this is worth investigating.

![h190303-12](https://user-images.githubusercontent.com/6989799/53763723-538d0e80-3e80-11e9-81c3-11fc0036c19d.jpg)

**Comment by biblepay** [comment]
POG retired.
