### ISSUE TITLE
exec bankroll: Unable to locate coins not marked as POG bankroll denominations.

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay#92]
I have only 60 BBP in a non-tithe address.
The other one, 1718 BBP, is a tithe address, but is not .001 denomination.

| Below is how the BBP looks in tree mode:  |
|:---|
| ![h190304-17](https://user-images.githubusercontent.com/6989799/53787739-a5f81a80-3ed4-11e9-9f5f-e0e6c7f422e4.jpg) |

| I'm unable to create a .001 denomination. |
|:---|
| ![h190304-18](https://user-images.githubusercontent.com/6989799/53787742-a7294780-3ed4-11e9-8e7a-77570907cdee.jpg) |

| If I move the 1718 out to a non-tithe address: |
|:---|
| ![h190304-19](https://user-images.githubusercontent.com/6989799/53787945-30407e80-3ed5-11e9-8475-1f8dde212ae4.jpg) |

| I still can not do exec bankroll. |
|:---|
| ![h190304-21](https://user-images.githubusercontent.com/6989799/53788161-d55b5700-3ed5-11e9-97d4-66518abd2551.jpg) |

| After I moved the 60 to the same address as 1718, I was able to finally perform the `exec bankroll`. I'm not sure if the two addresses have to be the same or the 60 BBP could not be a "change" address. |
|:---|
| ![h190304-23](https://user-images.githubusercontent.com/6989799/53788317-4f8bdb80-3ed6-11e9-8e3c-0a4c331fdbaa.jpg) |

**Comment by biblepay** [comment]
Please open in the Evo thread if this is still happening.
