### ISSUE TITLE
Tithe inputs have wrong decimal separator

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#93]
Here is screenshot 
![image](https://user-images.githubusercontent.com/10445226/53789453-103ca980-3f2d-11e9-97b7-03ab3d10c503.png)

Sending tithe cuts everything after decimal separator.
For example if I tithe 9,46 actual tithe us 9.00

Selected language is English and OS locale is Finnish
Windows 7
Wallet is 64 bits

**Comment by sunk818** [comment]
I mentioned this to @MIPPL on Discord, but I'm glad you posted this here.

**Comment by vahtis** [comment]
I did mention it too.
