### ISSUE TITLE
Tithing from PoG engine room does not preserve denomination

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#94]
This tithe is from engine room

Transaction ID: 4c92423c5e27bc4fc54424f9f3ffda63545c79ce7ee2671333f40538dbdc549d-000

Debug information

Debit: -1979.00100000 Biblepay
Credit: 1970.00092360 Biblepay

---------------------------------------------------------------------

This is automatic
Transaction ID: e62e6f227b48182fdbdc1763ce79cf86f7e21075d568c24b2d13c2487589145a-000

Debug information

Debit: -2978.00100000 Biblepay
Credit: 0.87041281 Biblepay
Credit: 2968.00100000 Biblepay

**Comment by sunk818** [comment]
@vahtis what happens when you go to tools, debug console, and do a `tithe 9`? How many outputs do you get? If you get two outputs (one to donation, and big chunk as change), I wonder if PoG Engine Room is using the `tithe` command line to perform the action.

**Comment by vahtis** [comment]
Debug information

Debit: -2968.00100000 Biblepay
Credit: 1.39990220 Biblepay
Credit: 2957.00100000 Biblepay
