### ISSUE TITLE
Add collecting small tithe changes into one big

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#97]
As tithing leaves now small changes <2 BBP. 
Add command to collect them into one address

**Comment by sunk818** [comment]
I commented in [1.1.9.6 release](https://github.com/biblepay/biblepay/commit/6d4a30742281fed1b513a00299009bf39c039cc9#commitcomment-32648864), but I'll post it here:

> It'd be better if tithe change (0.5 to 1.5 BBP) goes to a consistent but separate address other than tithe. For some reason, exec bankroll won't work to consolidate these small amounts. So, what I've been resorting to is sending all these small amounts to another address. Once sent, I can do an exec bankroll to gather all these small amounts into 100 BBP for example.

**Comment by vahtis** [comment]
@sunk818 idea is also good. I don't mind how the actual problem is solved

**Comment by sunk818** [comment]
I feel `exec bankroll` should work so that these small amounts are included when you do an exec bankroll. I don't care for another command. I think vahthis and I are asking for these other changes bbp it really wouldn't ask if `exec bankroll` was "smarter" about inputs that it selects.

**Comment by biblepay** [comment]
In Evo, we use multiple inputs now (in contrast to one), so coins actually get consolidated now.

No longer an issue.
