### ISSUE TITLE
PoG leaderboard does not highlight if nickname is not set

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#98]

**Comment by OrbisPictus** [comment]
I have different problem with leaderboard. I've setted nickname, but in WIN 1198 there is sometimes highlighted other nickname, not mine :) Even when I click on my nickname, after few seconds (refresh), It is highlighted other nickname. This happend only when I sort it by some column. It looks that it "jumps" after refresh to the position based on mine pog leaderboard id.

**Comment by biblepay** [comment]
POG has been removed.

**Comment by sunk818** [comment]
You have not removed it completely. You can still select PoG leaderboard from a menu and will crash the QT wallet.
